spring.application.name=backend

# Database - Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-gentle-wind-apx67uty.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oKFQ7hXxyM4P
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port
server.port=${PORT:8082}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=utprekshulousg@gmail.com
spring.mail.password=buhv gvdg koxg njxm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=c3BlbnZhU2VjcmV0S2V5Rm9ySldUU2lnbmluZzIwMjRTcGVudmFBcHA=